### ISSUE TITLE
How to get the json file to generate metadata_no_overlap?

### ISSUE THREAD

**Issue by fjiang9** [popcornell/SparseLibriMix#1]
Thanks for sharing the code! 
I'm trying to generate SparseLibriMix with more than 3 speakers. I guess I need to run generate_metadata_no_overlap.py first. But I cannot find the json file to run it.
https://github.com/popcornell/SparseLibriMix/blob/c340432658377675cd56f2d8cc84fbd4535dcc84/scripts/generate_metadata_no_overlap.py#L13-L14

**Comment by mpariente** [comment]
That's the output file of parse_utterances I guess. 
You need the LibriSpeech files and the forced alignements (textgrid files) from zenodo.

**Comment by mpariente** [comment]
I think that's the one: https://zenodo.org/record/2619474#.XwiHMhF8Lg4

**Comment by fjiang9** [comment]
> That's the output file of parse_utterances I guess.
> You need the LibriSpeech files and the forced alignements (textgrid files) from zenodo.

Thanks for your reply! But a new issue, I can't find the build_utterance_list function. https://github.com/popcornell/SparseLibriMix/blob/c340432658377675cd56f2d8cc84fbd4535dcc84/scripts/parse_utterances.py#L2

**Comment by popcornell** [comment]
Gonna fix this, thanks for pointing this out. I totally forgot about including that file !

**Comment by popcornell** [comment]
Tell me if it is fixed, sorry for the late reply.

**Comment by fjiang9** [comment]
Now it's fixed. Thanks!

**Comment by popcornell** [comment]
Nice to hear that. Closing this issue.
